id: IF7FD4B50
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:22:04+00:00'
last_modified: '2022-06-08T12:58:58.840820+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6700
  title: རྒྱ་བོད་ཤན་སྦྱར་གྱི་དངུལ་རྩའི་ཐ་སྙད་ཚིག་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    EC19:
      image_group_id: I3CN6702
      title: ''
      total_pages: 296
      order: 1
      base_file: EC19.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
